### ISSUE TITLE
Can't Load Script

### ISSUE THREAD

**Issue by Grokstreet** [antis0007/sd-webui-multiple-hypernetworks#13]
Apologies if this is something really dumb, but I get this error when installing + running with Automatic1111

Error loading script: multiple_hypernetworks.py
Traceback (most recent call last):
  File "F:\Stable Diffusion\stable-diffusion-webui\modules\scripts.py", line 195, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "F:\Stable Diffusion\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    compiled = compile(text, path, 'exec')
  File "F:\Stable Diffusion\stable-diffusion-webui\scripts\multiple_hypernetworks.py", line 71
    <title>sd-webui-multiple-hypernetworks/multiple_hypernetworks.py at main · antis0007/sd-webui-multiple-hypernetworks · GitHub</title>
                                                                             ^
SyntaxError: invalid character '·' (U+00B7)

**Comment by antis0007** [comment]
@Grokstreet It looks like your multiple_hypernetworks.py file contains a line that shouldn't be there. Not sure how you ended up with html code in the python file, but try cloning from the repo again and replacing your script file.

**Comment by Grokstreet** [comment]
Fixed! Thank you!
